# Generated by Django 4.2.13 on 2024-06-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('media', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('sights_landmarks', 'Sights & Landmarks'), ('cities_towns', 'Cities & Towns'), ('food_dining', 'Food & Dining'), ('cafes', 'Cafés'), ('activities_leisure', 'Activities & Leisure'), ('daily_life', 'Daily Life Essentials'), ('travel_tips', 'Travel Tips')], max_length=50)),
                ('author', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
